export default  {
  // for todo app
  TODO_ADD: 'TODO_ADD',
  TODO_DELETE: 'TODO_DELETE',
  TODO_TOGGLE: 'TODO_TOGGLE',

  // global state
  USER_ADD: 'USER_ADD',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_LIST: 'USER_LIST',

  API_REQUEST: 'API_REQUEST',
  API_SUCCESS: 'API_SUCCESS',
  API_ERROR: 'API_ERROR',
  API_RESET: 'API_RESET'

}